spring.application.name=FriendBirthday

# Railway dynamic port
server.port=${PORT:8080}

# Disable DB for now (important for deployment)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Optional (clean logs)
spring.jpa.show-sql=true
